imgstudybuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('stations/', include('stations.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('meetings/', include('meeting_calendar.urls')),
    path('study-buddies/', include('study_buddies.urls')),
    path('coaches/', include('coaches.urls')),
    path('raviews-and-ratings/', include('review_ratings.urls')),
    path('offers/', include('offers.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path
from . import views


app_name = 'offers'
urlpatterns = [
    path('offer-details/<int:offer_id>',views.offer_details, name='offer_details'),  
    path('create-offer',views.create_offer, name='create_offer'),
    path('offers',views.offers, name='offers'),
    # to be delete
    path('create-offer-json',views.create_offer_json, name='create_offer_json'),
    path('accept-or-reject-offer/<int:offer_id>/<str:status>',views.accept_or_reject_offer, name='accept_or_reject_offer'),
]

stations/urls.py
from django.urls import path
from . import views

app_name = 'stations'

urlpatterns = [
    path('first-level-stations',views.first_level_stations,name='first_level_stations'),
    path('create-first-level-station',views.create_first_level_station,name='create_first_level_station'),
    path('edit-first-level-station/<int:id>',views.edit_first_level_station,name='edit_first_level_station'),
    path('delete-first-level-station/<int:id>',views.delete_first_level_station,name='delete_first_level_station'),

    path('second-level-stations',views.second_level_stations,name='second_level_stations'),  
    path('create-second-level-station',views.create_second_level_station,name='create_second_level_station'),
    path('edit-second-level-station/<int:id>',views.edit_second_level_station,name='edit_second_level_station'),
    path('delete-second-level-station/<int:id>',views.delete_second_level_station,name='delete_second_level_station'),

    path('third-level-stations',views.third_level_stations,name='third_level_stations'),
    path('create-third-level-stations',views.create_third_level_station,name='create_third_level_station'),
    path('edit-third-level-station/<int:id>',views.edit_third_level_station,name='edit_third_level_station'),
    path('delete-third-level-station/<int:id>',views.delete_third_level_station,name='delete_third_level_station'),

    path('station-creator/',views.station_creator,name='station_creator'),
    path('stations-admin/',views.stations_admin,name='stations'),

    path('stations',views.first_level_station_view,name='first_level_station_view'),
    path('stations/2/<int:id>',views.second_level_station_view,name='second_level_station_view'),
    path('stations/3/<int:id>',views.third_level_station_view,name='third_level_station_view'),

    path('stations-menu/<int:id>/<str:title>',views.stations_menu_view,name='stations_menu_view'),
    path('station-practice/<int:id>/<str:type>',views.station_practice,name='station_practice'),

]

stations/forms.py
from django import forms
from . import models

form_control = {'class': 'form-control'}

def get_all_stations():
    stations = models.ThirdLevelStation.objects.all()
    for station in stations:   
      exists = models.ExaminerMarkSheet.objects.filter(station = station).exists()
      if exists:
        stations.exclude(id = station.id)
    choices = [(station.id, station.title) for station in stations]
    return choices


class FirstLevelStationForm(forms.ModelForm):
  class Meta:
    model = models.FirstLevelStation
    widgets = {
      'title': forms.widgets.TextInput(attrs=form_control)
    }
    labels = {
        'title':'First Level Station Name'
    }
    fields = ['title',]

class SecondLevelStationForm(forms.ModelForm):
  class Meta:
    model = models.SecondLevelStation
    widgets = {
      'title': forms.widgets.TextInput(attrs=form_control)
    }
    labels = {
        'title':'Second Level Station Name'
    }

    fields = ['first_level_station','title',]

class ThirdLevelStationForm(forms.ModelForm):
  class Meta:
    model = models.ThirdLevelStation
    widgets = {
      'title': forms.widgets.TextInput(attrs=form_control)
    }
    labels = {
        'title':'Third Level Station Name'
    }
    fields = ['second_level_station','title',]

class StationForm(forms.Form):
  station = forms.ChoiceField(label="Station", choices=get_all_stations())


class CandidateInstructionForm(forms.ModelForm):
  class Meta:
    model = models.CandidateInstruction
    widgets = {
      'heading': forms.widgets.Select(attrs={'class':'form-select form-control'}),
      'text': forms.widgets.Textarea(attrs={'class':'form-control','rows':1})
    }
    fields = ['heading','text',]

class PatientDisclosureForm(forms.ModelForm):
  class Meta:
    model = models.PatientInstruction
    widgets = {
      'heading': forms.widgets.Select(attrs={'class':'form-select form-control'}),
      'text': forms.widgets.Textarea(attrs={'class':'form-control','rows':1})
    }
    fields = ['heading','text',]

class ExaminerMarkSheetForm(forms.ModelForm):
  class Meta:
    model = models.ExaminerMarkSheet
    widgets = {
      'heading': forms.widgets.Select(attrs={'class':'form-select form-control'})
    }
    fields = ['heading']

stations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from core.decorators import role_required, subscription_required
from core.enums import RoleEnum
from . import forms
from . import models
from . import utils
from core.utils import paginator


# Create your views here.


## stations
@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def first_level_stations(request):
    template_name = "first_level_station/first_level_stations.html"
    first_level_stations_ = models.FirstLevelStation.objects.all()
    return render(
        request,
        template_name,
        {"items": paginator(request, first_level_stations_, 10)},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def create_first_level_station(request):
    template_name = "first_level_station/create_first_level_station.html"
    form = forms.FirstLevelStationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "First level station successfully created.")
            return redirect("stations:first_level_stations")
    return render(request, template_name, {"form": form, "type": "create"})


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def edit_first_level_station(request, id):
    first_level_station_ = get_object_or_404(models.FirstLevelStation, id=id)
    form = forms.FirstLevelStationForm(
        request.POST or None, instance=first_level_station_
    )
    template_name = "first_level_station/create_first_level_station.html"
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"First level station {first_level_station_.title} successfully updated.",
            )
            return redirect("stations:first_level_stations")
    return render(
        request,
        template_name,
        {"form": form, "type": "edit", "obj": first_level_station_},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def delete_first_level_station(request, id):
    first_level_station = get_object_or_404(models.FirstLevelStation, id=id)
    template_name = "first_level_station/delete_first_level_station.html"
    if request.method == "POST":
        first_level_station.delete()
        messages.success(
            request,
            f"First level station {first_level_station.title} successfully deleted.",
        )
        return redirect("stations:first_level_stations")
    return render(request, template_name, {"obj": first_level_station})


## stations categories
@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def second_level_stations(request):
    template_name = "second_level_station/second_level_stations.html"
    second_level_stations_ = models.SecondLevelStation.objects.all()
    return render(
        request,
        template_name,
        {"items": paginator(request, second_level_stations_, 10)},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def create_second_level_station(request):
    template_name = "second_level_station/create_second_level_station.html"
    form = forms.SecondLevelStationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Second level station successfully created.")
            return redirect("stations:second_level_stations")
    return render(request, template_name, {"form": form, "type": "create"})


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def edit_second_level_station(request, id):
    second_level_station = get_object_or_404(models.SecondLevelStation, id=id)
    form = forms.SecondLevelStationForm(
        request.POST or None, instance=second_level_station
    )
    template_name = "second_level_station/create_second_level_station.html"
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"Second level station {second_level_station.title} successfully updated.",
            )
            return redirect("stations:second_level_stations")
    return render(
        request,
        template_name,
        {"form": form, "type": "edit", "obj": second_level_station},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def delete_second_level_station(request, id):
    second_level_station = get_object_or_404(models.SecondLevelStation, id=id)
    template_name = "second_level_station/delete_second_level_station.html"
    if request.method == "POST":
        second_level_station.delete()
        messages.success(
            request,
            f"Second level station {second_level_station.title} successfully deleted.",
        )
        return redirect("stations:second_level_stations")
    return render(request, template_name, {"obj": second_level_station})


## stations sub categories
@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def third_level_stations(request):
    template_name = "third_level_station/third_level_stations.html"
    third_level_stations_ = models.ThirdLevelStation.objects.all()
    return render(
        request,
        template_name,
        {"items": paginator(request, third_level_stations_, 10)},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def create_third_level_station(request):
    template_name = "third_level_station/create_third_level_station.html"
    form = forms.ThirdLevelStationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Second level station successfully created.")
            return redirect("stations:third_level_stations")
    return render(request, template_name, {"form": form, "type": "create"})


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def edit_third_level_station(request, id):
    third_level_station = get_object_or_404(models.ThirdLevelStation, id=id)
    form = forms.ThirdLevelStationForm(
        request.POST or None, instance=third_level_station
    )
    template_name = "third_level_station/create_third_level_station.html"
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"Second level station {third_level_station.title} successfully updated.",
            )
            return redirect("stations:third_level_stations")
    return render(
        request,
        template_name,
        {"form": form, "type": "edit", "obj": third_level_station},
    )


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def delete_third_level_station(request, id):
    third_level_station = get_object_or_404(models.ThirdLevelStation, id=id)
    template_name = "third_level_station/delete_third_level_station.html"
    if request.method == "POST":
        third_level_station.delete()
        messages.success(
            request,
            f"Second level station  {third_level_station.title} successfully deleted.",
        )
        return redirect("stations:third_level_stations")
    return render(request, template_name, {"obj": third_level_station})


@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def station_creator(request):
    template_name = "station_creator.html"
    if request.method == "POST":
        # Station Details
        station = get_object_or_404(
            models.ThirdLevelStation, id = request.POST.get('third_level_station')
        )
        station_exists = models.ExaminerMarkSheet.objects.filter(station=station).exists()
        if not station_exists:
            utils.save_instruction_bulk(
                station,
                request.POST.getlist("candidate_instruction_heading"),
                request.POST.getlist("candidate_instruction_text"),
                request.POST.getlist("patient_instruction_heading"),
                request.POST.getlist("patient_instruction_text"),
            )
            # Examiner Mark Sheet
            # has_station = models.ExaminerMarkSheet.objects.filter(station=station).exists()
            utils.save_mark_sheet_bulk(
                station,
                request.POST.getlist("data_gathering_text"),
                request.POST.getlist("management_text"),
                request.POST.getlist("interpersonal_skills_text"),
            )
            # station Approach
            utils.save_station_approach(
                station,
                request.POST.get("station_approach_learning_points"),
                request.POST.getlist("station_approach_link"),
            )
            messages.success(request,f"Sation {station.title} was successfully created.")
        else:
            messages.error(request,f"Sation {station.title} already exists.")
        return redirect('stations:stations')
    context = {
        "stations": utils.get_all_stations(),
        "candidate_instruction_inquiry_choices": models.CandidateInstruction.Inquiry,
        "patient_instruction_disclosure_choices": models.PatientInstruction.Disclosure,
    }
    return render(request, template_name, context)

@role_required(allowed_roles=[RoleEnum.ADMIN.value])
def stations_admin(request):
    template_name = "station/stations.html"
    station_ = models.FirstLevelStation.objects.all()
    return render(
        request,
        template_name,
        {"items": paginator(request, station_, 10)}
    )

#User views
@subscription_required
@role_required(allowed_roles=[RoleEnum.ADMIN.value,RoleEnum.CANDIDATE.value])
def first_level_station_view(request):
    template_name = "first_level_station/first_level_station_view.html"
    station_ = models.FirstLevelStation.objects.all()
    return render(
        request,
        template_name,
        {"items": paginator(request, station_, 10)}
    )

@role_required(allowed_roles=[RoleEnum.ADMIN.value,RoleEnum.CANDIDATE.value])

stations/templates/station_category/create_category_station.html
{% extends 'main_shared.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
 {% include 'snippets/title_text.html' %} Second Level Sation
{% endblock %}
{% block content %}
<h5 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Home / Second Level Sations /</span>
    {% include 'snippets/title_text.html' %} Second Level Sation
   </h5>
<div class="card mb-4">
   {% if type == 'create' %}
   <form class="card-body"  action="{% url 'stations:create_second_level_station' %}" method="POST">
      {% else %}
   <form class="card-body"  action="{% url 'stations:edit_second_level_station' obj.id  %}" method="POST">
   {% endif %}

      {% csrf_token %} 
     <div class="row g-3">
        <div class="col-md-6">
            {{form.first_level_station|as_crispy_field}}
          </div>
       <div class="col-md-6">
         {{form.title|as_crispy_field}}
       </div>
     </div>
     <div class="pt-4">
       <button type="submit" class="btn btn-primary me-sm-3 me-1">
        {% include 'snippets/title_text.html' %} Second Level Sation
       </button>
       <a href="{% url 'stations:second_level_stations' %}" class="btn btn-label-secondary">Cancel</a>
     </div>
   </form>
 </div>

{% endblock %}

stations/templates/station_category/delete_category_station.html
{% extends 'main_shared.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{obj.title|title}}{% endblock %}
{% block content %}
<h5 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Home / Second Level Sations /</span> Delete {{obj.title|title}}</h5>
<div class="card mb-4">

   <form class="card-body"  action="{% url 'stations:delete_second_level_station' obj.id %}" method="POST">
      {% csrf_token %}
     <div class="row g-3 mt-2">
       <div class="col-md-12">
        <h4>Are you sure you want to delete station <strong>{{obj.title|title}}</strong></h4>
       </div>
     </div>
     <div class="pt-4">
       <button type="submit" class="btn btn-danger me-sm-3 me-1">       
            Delete Second Level Sation
       </button>
       <a href="{% url 'stations:second_level_stations' %}" class="btn btn-label-secondary">Cancel</a>
     </div>
   </form>
 </div>

{% endblock %}

stations/templates/station_category/station_categories.html
{% extends 'main_shared.html' %}
{% load static %}
{% load static %}
{% block title %}Second Level Station{% endblock %}
{% block content %}
<h5 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Home /</span> Second Level Sations </h5>
<div class="card-header flex-column flex-md-row mb-3">
     
    <div class="dt-action-buttons pt-3 pt-md-0">
        <div class="dt-buttons btn-group flex-wrap"> 
            <div class="btn-group">
         
            </div> 
            <a class="btn btn-secondary create-new btn-primary" href="{% url 'stations:create_second_level_station' %}">
                <span>
                    <i class="bx bx-plus me-sm-1"></i> 
                    <span class="d-none d-sm-inline-block">Add Second Level Station</span>
                </span>
            </a> 
        </div>
    </div>

{% if messages %}
{% for message in messages %}

<div class="alert alert-{{ message.tags }} alert-dismissible mt-3" role="alert">
  <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
  </button>
  {{ message }}
</div>
{% endfor %}
{% endif %}

</div>
  <div class="card">

  
    <div class="table-responsive">
      <table class="table border-top table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Second Level Station</th> 
            <th>First Level Station</th> 
            <th>Date</th>
            <th>Action</th>
          </tr>
        </thead>
        
        <tbody>
          {% for item in items %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{item.title|title}}</td>
            <td>{{item.first_level_station.title|title}}</td>
            <td>{{item.timestamp}}</td>
            <td>
              <div class="dropdown">
                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bx bx-dots-vertical-rounded"></i>
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'stations:edit_second_level_station' item.id %}"><i class="bx bx-edit-alt me-1"></i> Edit</a>
                  <a class="dropdown-item" href="{% url 'stations:delete_second_level_station' item.id %}"><i class="bx bx-trash me-1"></i> Delete</a>
                </div>
              </div>
            </td>

          </tr>
          {% empty %}
          <tr>
            <td>No data</td>
          </tr>
          {% endfor %}
        </tbody>
      
      </table>
    </div>
  {% if items %}
  {% include 'snippets/pagination.html' with items=items %}
  {% endif %}
  </div>


{% endblock %}