accounts/urls.py
from django.urls import path
from .views import (auth,dashboard,applications) 

app_name = 'accounts'

urlpatterns = [
    path('login',auth.login, name='login'),
    path('',auth.redirect_logged, name='redirect_logged'),
    path('not-authorized-404',auth.not_authorized, name='not_authorized'),
    path('logout',auth.my_logout, name='logout'),

    path('dashboard/admin/',dashboard.admin_dashboard, name='admin_dashboard'),
    path('dashboard/candidate/',dashboard.candidate_dashboard, name='candidate_dashboard'),
    path('dashboard/coach',dashboard.coach_dashboard, name='coach_dashboard'),
    path('profile',dashboard.profile, name='profile'),
    path('public-profile/<uuid:user_id>',dashboard.public_profile,name='public_profile'),
    path('users',dashboard.users, name='users'),
    path('admin-profile/<uuid:coach_id>',dashboard.admin_profile, name='admin_profile'),
    path('activate-or-deactivate_account/<uuid:user_id>',dashboard.activate_or_deactivate_account, name='activate_or_deactivate_account'),
    path('add-admin',dashboard.add_admin, name='add_admin'),
    path('change-password',dashboard.change_password, name='change_password'),
    path('upload-profile-picture',dashboard.upload_profile_picture, name='upload_profile_picture'),
    path('update-personal-details',dashboard.update_personal_details, name='update_personal_details'),
    path('update-general-additional-info',dashboard.update_general_additional_info, name='update_general_additional_info'),
    path('update-exam-date',dashboard.update_exam_date, name='update_exam_date'),

    path('register-study-buddy',auth.StudyBuddyDataWizard.as_view(),name='register_study_buddy')
]

imgstudybuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('stations/', include('stations.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('meetings/', include('meeting_calendar.urls')),
    path('study-buddies/', include('study_buddies.urls')),
    path('coaches/', include('coaches.urls')),
    path('raviews-and-ratings/', include('review_ratings.urls')),
    path('offers/', include('offers.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path
from . import views


app_name = 'offers'
urlpatterns = [
    path('offer-details/<int:offer_id>',views.offer_details, name='offer_details'),  
    path('create-offer',views.create_offer, name='create_offer'),
    path('offers',views.offers, name='offers'),
    # to be delete
    path('create-offer-json',views.create_offer_json, name='create_offer_json'),
    path('accept-or-reject-offer/<int:offer_id>/<str:status>',views.accept_or_reject_offer, name='accept_or_reject_offer'),
]

review_ratings/urls.py
from django.urls import path
from . import views


app_name = 'review_ratings'
urlpatterns = [
    path('create-review/<uuid:user_id>',views.create_review, name='create_review'),
    path('create-offer-review/<int:product_id>',views.create_offer_review, name='create_offer_review')
]

offers/models.py
from django.db import models
from django.conf import settings
from django.db.models import Avg, Count
from tinymce.models import HTMLField



User = settings.AUTH_USER_MODEL
# Create your models here.

class OfferReviewRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_review')
    offer = models.ForeignKey('Offer', on_delete=models.CASCADE,related_name='offer_review')
    review = HTMLField()
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        ordering = ["timestamp",]

class Offer(models.Model):
    PENDING ='pending'
    STATUS = (('accepted','Accepted'),('rejected','Rejected'),(PENDING,'Pending'))
    user=models.ForeignKey(User,related_name='user_offers', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='offers')
    file = models.FileField(upload_to='files', null=True,blank=True)
    summary = HTMLField()
    description = HTMLField()
    price = models.FloatField(default=0.00)
    status = models.CharField(max_length=10,choices=STATUS,default=PENDING)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
         return self.title

    class Meta:
        ordering = ["-timestamp", ]


    def averageReview(self):
        reviews = OfferReviewRating.objects.filter(offer=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = OfferReviewRating.objects.filter(offer=self).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

offers/forms.py
from django import forms
from . import models
from tinymce.widgets import TinyMCE

class OfferForm(forms.ModelForm):
    class Meta:
        model = models.Offer
        widgets = {
          'summary': TinyMCE(attrs={'rows':4}),
          'description': TinyMCE(attrs={'rows':4}),
          'file': forms.FileInput(attrs={'accept': 'application/pdf'}),
          'image': forms.FileInput(attrs={'accept': 'image/png, image/jpeg, image/jpg'})
        }
        fields = ('title','image','file','summary','description','price')

offers/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import models
from .forms import OfferForm
# Create your views here.

@login_required
def offer_details(request,offer_id):
    template_name = 'offer_details.html'
    obj = get_object_or_404(models.Offer,id=offer_id)
    context ={'obj':obj}
    return render(request,template_name,context)

@login_required
def offers(request):
    template_name = 'offers.html'
    offers_qs = models.Offer.objects.filter(user = request.user)
    context = {
        "offers":offers_qs
    }
    return render(request,template_name,context)

@login_required
def create_offer(request):
    template_name = 'create_offer.html'
    form = OfferForm(request.POST or None,request.FILES or None)
    print(form.errors.as_data())
    if request.method == 'POST':
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request,"offer successfully added.")
            return redirect("offers:offers")
    return render(request,template_name, {'form':form})

@login_required
def create_offer_json(request):
    if request.method == 'POST':
        user=request.user
        title=request.POST.get('title')
        image=request.FILES.get('image')
        summary =request.POST.get('summary')
        description =request.POST.get('description')
        price = request.POST.get('price')
        print("title >>>" + title)
        print("description >>>" + description)
        new_offer = models.Offer(user=user,title=title,image=image,description=description,summary=summary,price=price)
        new_offer.save()
        data = {'title':new_offer.title,'summary':new_offer.summary,'description':new_offer.description,'price':new_offer.price,'image':new_offer.image.url }
        return JsonResponse(data)
    return JsonResponse({"error":"something went wrong"})

@login_required
def accept_or_reject_offer(request,offer_id,status):
    obj = get_object_or_404(models.Offer,id=offer_id)
    subject = 'Offer content was not approved.'
    message = f'Hi, {obj.user.get_full_name()}, your content offer was not approved.'
    obj.status = status
    obj.save()
    if status == 'accepted':
        subject ='Offer content was approved'
        message = f'Hi, {obj.user.get_full_name()}, congradulations, your content offer titled "{obj.title}" was approved.'
    messages.success(request,"Offer was successfully {}".format(status))
    # Send email for decline or approval
    return redirect('/')

offers/templates/create_offer.html
{% extends 'shared.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Create Offer {% endblock %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-style1">
        <li class="breadcrumb-item">
            <a href="{% url 'accounts:redirect_logged' %}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'accounts:profile' %}">Profile</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'offers:offers' %}">Offers</a>
        </li>
        <li class="breadcrumb-item active">Create Offer</li>
    </ol>
</nav>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
    </button>
    {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 class="mb-0">Create Offer </h5>
      <small class="text-muted float-end">offers</small>
    </div>
    <div class="card-body">
        <form action="{% url 'offers:create_offer' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.title|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.price|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.image|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.file|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        {{ form.summary|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>

            </div>
      
        <div class="modal-footer">
            <a href="{% url 'accounts:profile' %}" class="btn btn-warning">
                Cancel
            </a>
            <button type="submit" class="btn btn-primary">Create Offer</button>
        </div>
        </form>
        </div>
    </div>
  </div>






{% endblock %}

offers/templates/offer_details.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}{{obj.title|title}}{% endblock %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-style1">
      <li class="breadcrumb-item">
        <a href="{% url 'accounts:redirect_logged' %}">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{% url 'accounts:profile' %}">Profile</a> 
      </li>
      {% if request.user.is_coach %}
      <li class="breadcrumb-item">
        <a href="{% url 'offers:offers' %}">Offers</a>
      </li>
      {% endif %}
      <li class="breadcrumb-item active">{{obj.title|title}}</li>
    </ol>
  </nav>

<div class="card mb-3">


  <div class="row g-0">
    <div class="col-md-12">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
          </button>
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="col-md-4">
      <img class="card-img card-img-left" src="{{obj.image.url}}" alt="tallu tabis" style="height:260px;width:100%;object-fit:cover; object-position: 100% 0; padding: 1.5em 0 0 1.5em;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{obj.title|title}}</h5>
        <p class="card-text">{{obj.summary|safe}}</p>
        <span>{% include 'snippets/ratings.html' with obj=obj %} {{obj.countReview}} Reviews</span>
        {% if request.user.is_candidate %}
        <div class="mt-3">
            <a href="#" class="btn btn-primary">Request Offer £{{obj.price|floatformat:2}}</a>
        </div>
        {% endif %}
      </div>
    </div>
    <!-- Motivations -->
    
    <div class="col-md-12">
      <div class="card-body">
        <p class="card-text">{{obj.description|safe}}</p>
      </div>
    </div>
    <hr>
    
    <div class="col-md-12">
        <div class="card-body">
          <h3 class="mb-5">{{obj.countReview}} Reviews</h3>
          <div class="row mb-5">
            {% for review in obj.offer_review.all %}
            <ul class="col-12 commented pl-0">
              <li class="comm-inf">

                <div class="col-md-12 comments-info">
                  <div class="conra">
                    <h5 class="mb-2">{{review.timestamp}} by {{review.user.get_full_name|title}}</h5>
                    <div class="rating-box">
                      <div class="detail-list-rating mr-0">
                        <i class="fa fa-star{% if review.rating < 0.5 %}-o{% elif review.rating >= 0.5 and review.rating < 1 %}-half-o {% endif %}"
                          aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating < 1.5 %}-o{% elif review.rating >= 1.5 and review.rating < 2 %}-half-o {% endif %}"
                          aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating < 2.5 %}-o{% elif review.rating >= 2.5 and review.rating < 3 %}-half-o {% endif %}"
                          aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating < 3.5 %}-o{% elif review.rating >= 3.5 and review.rating < 4 %}-half-o {% endif %}"
                          aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating < 4.5 %}-o{% elif review.rating >= 4.5 and review.rating < 5 %}-half-o {% endif %}"
                          aria-hidden="true"></i>
                        {{review.rating}}
                      </div>
                    </div>

                  </div>
                  <!-- <p class="mb-4">{{review.timestamp}}</p> -->
                  <p>{{review.review}}</p>

                </div>
              </li>

            </ul>
            {% empty %}
            <h5>No reviews</h5>
            {% endfor %}
          </div>
        </div>

      </div>
      {% if request.user.is_candidate %}
    <hr>
    <div class="col-md-12">

      <div class="card-body">
        <!-- Leave Rating -->
        <h3 class="mb-3">Add Review</h3>
        <span>Your rating for this  Product </span>
        <form action="{% url 'review_ratings:create_offer_review' obj.id %}" method="POST">
         {% csrf_token %}
          <div class="clearfix"></div>

          <!-- Rating stars -->
          <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5"><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5"><label for="rating9" title="4.5" class="half"></label>
            <input type="radio" name="rating" id="rating8" value="4"><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5"><label for="rating7" title="3.5" class="half"></label>
            <input type="radio" name="rating" id="rating6" value="3"><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5"><label for="rating5" title="2.5" class="half"></label>
            <input type="radio" name="rating" id="rating4" value="2"><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5"><label for="rating3" title="1.5" class="half"></label>
            <input type="radio" name="rating" id="rating2" value="1"><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5"><label for="rating1" title="0.5" class="half"></label>
          </div>
          <div class="clearfix"></div>
          <div class="mb-3">

            <div class="input-group">
              <textarea id="basic-icon-default-message" name="review" class="form-control" placeholder="Review"></textarea>
            </div>

          </div>
          <button type="submit" class="btn btn-primary">Submit Review</button>
        </form>
      </div>
    </div>
  {% endif %}
  </div>
</div>

{% endblock %}

offers/templates/offers.html
{% extends 'shared.html' %}
{% load static %}
{% block title %}Offers{% endblock %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-style1">
    <li class="breadcrumb-item">
      <a href="{% url 'accounts:redirect_logged' %}">Home</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'accounts:profile' %}">Profile</a>

    </li>
    <li class="breadcrumb-item active">Offers</li>
  </ol>
</nav>

<div class="row">
  <div class="col-md-12 mb-5">
    <a href="{% url 'offers:create_offer' %}" class="btn btn-primary">Add Offer</a>
    <!-- <a href="#" class="btn btn-primary">Add Offer</a> -->
  </div>
  <div class="col-md-12" id="offerSuccessMsg">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
      </button>
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
  </div>
  {% for offer in offers %}
  <div class="col-md-4 mb-3">
    <div class="card h-100">
      <img class="card-img-top" src="{{ offer.image.url }}" alt="{{offer.title}}">
      <div class="card-body">
        <h5 class="card-title">{{offer.title|title}}</h5>
        <p class="card-text">
          {% if offer.status == 'pending' %}
            <span class="badge bg-label-warning"> {{offer.status}}</span>
          {% elif offer.status == 'rejected' %}         
            <span class="badge bg-label-danger">{{offer.status}}</span>
          {% else %}          
            <span class="badge bg-label-success">{{offer.status}}</span>
          {% endif %}
        </p>
        <p class="card-text">
          {{offer.title|truncatechars:20}}
        </p>
        <a href="{% url 'offers:offer_details' offer.id %}" class="btn btn-outline-primary me-2">Preview</a>
        <a href="#" class="btn btn-warning">Edit</a>
      </div>
    </div>
  </div>
  {% empty %}
  <h4>No offers</h4>
  {% endfor %}


</div>
<!-- Modal -->
<div class="modal fade" id="meetingModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="offersModal">Add Offer</h5>
        <hr>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="offersData">
          <div class="row">
            <div class="col-md-12">
              <div class="mb-3">
                <label for="image" class="form-label">Upload Offer Image</label>
                <input type="file" class="form-control" id="image" accept="image/jpeg, image/png">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control" id="title">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="number" min="0.01" step="0.01" class="form-control" id="price">
              </div>
            </div>
            <div class="col-md-12">
              <div class="mb-3">
                <label for="summary" class="form-label">Offer Summary</label>
                <textarea class="form-control" id="summary" rows="3" spellcheck="false" name="summary"></textarea>
              </div>
            </div>
            <div class="col-md-12">
              <div class="mb-3">
                <label for="description" class="form-label">Offer Description</label>
                <textarea class="form-control" id="description" rows="3" spellcheck="false" name="description"></textarea>
              </div>
            </div>

          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <button type="submit" class="btn btn-primary">Create Offer</button>
      </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}
{% block js %}
<script type="text/javascript">
  let formData = new FormData();
  document.getElementById("offersData").addEventListener("submit", (e) => {
    e.preventDefault();
    const URL = '{% url "offers:create_offer_json" %}';
    const title = document.getElementById('title').value;
    const image = document.getElementById('image').files[0];
    const price = document.getElementById('price').value;
    const summary = document.getElementById('summary').value;
    const description = document.getElementById('description').value;
    console.log(description)
    formData.append('title', title)
    formData.append('action', 'create')
    formData.append('image', image)
    formData.append('price', price)
    formData.append('summary', summary)
    formData.append('description', description)
    formData.append('csrfmiddlewaretoken', '{{csrf_token}}')
    fetch(URL, {
      method: 'POST',
      body: formData,
      enctype: 'multipart/form-data'
    }).then(res => res.json()).then(data => {
      location.reload();
      title = '';
      image = '';
      price = '';
      summary = '';
      description = '';
      //document.getElementById('offerSuccessMsg').innerHTML ='<div class="alert alert-success alert-dismissible" role="alert">Offer successfull added <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>'
    }).catch(err => console.log(err));
  })
</script>
{% endblock %}