accounts/urls.py
from django.urls import path
from .views import (auth,dashboard,applications) 

app_name = 'accounts'

urlpatterns = [
    path('login',auth.login, name='login'),
    path('',auth.redirect_logged, name='redirect_logged'),
    path('not-authorized-404',auth.not_authorized, name='not_authorized'),
    path('logout',auth.my_logout, name='logout'),

    path('dashboard/admin/',dashboard.admin_dashboard, name='admin_dashboard'),
    path('dashboard/candidate/',dashboard.candidate_dashboard, name='candidate_dashboard'),
    path('dashboard/coach',dashboard.coach_dashboard, name='coach_dashboard'),
    path('profile',dashboard.profile, name='profile'),
    path('public-profile/<uuid:user_id>',dashboard.public_profile,name='public_profile'),
    path('users',dashboard.users, name='users'),
    path('admin-profile/<uuid:coach_id>',dashboard.admin_profile, name='admin_profile'),
    path('activate-or-deactivate_account/<uuid:user_id>',dashboard.activate_or_deactivate_account, name='activate_or_deactivate_account'),
    path('add-admin',dashboard.add_admin, name='add_admin'),
    path('change-password',dashboard.change_password, name='change_password'),
    path('upload-profile-picture',dashboard.upload_profile_picture, name='upload_profile_picture'),
    path('update-personal-details',dashboard.update_personal_details, name='update_personal_details'),
    path('update-general-additional-info',dashboard.update_general_additional_info, name='update_general_additional_info'),
    path('update-exam-date',dashboard.update_exam_date, name='update_exam_date'),

    path('register-study-buddy',auth.StudyBuddyDataWizard.as_view(),name='register_study_buddy')
]

imgstudybuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('stations/', include('stations.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('meetings/', include('meeting_calendar.urls')),
    path('study-buddies/', include('study_buddies.urls')),
    path('coaches/', include('coaches.urls')),
    path('raviews-and-ratings/', include('review_ratings.urls')),
    path('offers/', include('offers.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

meeting_calendar/urls.py
from django.urls import path
from . import views


app_name = 'meeting_calendar'

urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('calendar/<int:id>/', views.CalendarView.as_view(), name='calendar'),
    path('availability/', views.availability, name='availability'),
    path('a/availability-and-session-expectation/', views.availability_and_session_expectation, name='availability_and_session_expectation'),
    path('availability/<uuid:user_id>/', views.availability, name='availability'),
    path('create-availability/', views.create_availability, name='create_availability'),
    path('remove-availability/<int:id>/', views.remove_availability, name='remove_availability'),
    path('remove-availability/<int:id>/<str:action>/', views.remove_availability, name='remove_availability'),
    path('q/book-a-meeting/<uuid:user_id>/', views.book_a_meeting_v1, name='book_a_meeting_v1'),
    path('book-a-meeting/<uuid:user_id>/', views.book_a_meeting, name='book_a_meeting'),
    path('meeting_detail/<int:meeting_id>/', views.meeting_detail, name='meeting_detail'),
    path('check-in-or-check-out/<int:meeting_id>/<str:check_type>/', views.check_in_or_check_out, name='check_in_or_check_out'),
    path('update-meeting-status/<int:meeting_id>/<str:status_type>/', views.update_meeting_status, name='update_meeting_status'),
    path('create-a-quick-meeting/',views.create_a_quick_meeting,name="create_a_quick_meeting"),
    path('accept-a-quick-meeting/<int:id>/',views.accept_a_quick_meeting,name="accept_a_quick_meeting"),
    path('meetings/',views.meetings,name="meetings"),

    # API
    path('get-availability/<uuid:requested_user_id>/<str:booking_date>/', views.get_availability,name='get_availability')
]

offers/urls.py
from django.urls import path
from . import views


app_name = 'offers'
urlpatterns = [
    path('offer-details/<int:offer_id>',views.offer_details, name='offer_details'),  
    path('create-offer',views.create_offer, name='create_offer'),
    path('offers',views.offers, name='offers'),
    # to be delete
    path('create-offer-json',views.create_offer_json, name='create_offer_json'),
    path('accept-or-reject-offer/<int:offer_id>/<str:status>',views.accept_or_reject_offer, name='accept_or_reject_offer'),
]

study_buddies/urls.py
from django.urls import path
from . import views


app_name = 'study_buddies'
urlpatterns = [
    path('all',views.view_all_study_buddies, name='view_all_study_buddies')

]

study_buddies/models.py
from django.db import models

# Create your models here.

study_buddies/views.py
import pytz
from django.db.models import Q
from django.shortcuts import render,redirect, get_object_or_404,get_list_or_404
from django.contrib.auth.decorators import login_required
from accounts.models import User
from django.core.paginator import Paginator

from core.enums import RoleEnum
from core.utils import paginator


# Create your views here.
@login_required
def view_all_study_buddies(request):
    template_name = 'view_all_study_buddies.html'
    candidates_qs =  User.objects.filter(role = RoleEnum.CANDIDATE.value).exclude(id = request.user.id)
    final_qs = ''
    time_zones = pytz.all_timezones_set

    if request.method== 'POST':
        time_zone = request.POST.get('time_zone_')
        exam_date = request.POST.get('exam_date')
        day = request.POST.get('day')
        if time_zone == '':
            time_zone = None
        if exam_date == '':
            exam_date = None
        if day == '':
            day = None
        final_qs= candidates_qs.filter(
            Q(user_availability__day = day)|
            Q (user_general_additional_info__time_zone=time_zone)|
            Q(study_buddy_additional_info__exam_date=exam_date)
            )
        
        context = {
            'obj':paginator(request,final_qs,25),
            'candidates':len(final_qs),
            'time_zones':time_zones,
            'time_zone':time_zone,
            'exam_date':exam_date,
            'day': day,
            'type':1
        }

        return render(request,template_name,context)
    final_qs = candidates_qs
    context = {
        'obj':paginator(request,final_qs,25),
        'candidates':len(final_qs),
        'time_zones':time_zones,
        'time_zone':'',
        'exam_date':'',
        'availability':'',
        'online_offline':'',
        'type':2
    }

    return render(request,template_name,context)

study_buddies/templates/view_all_study_buddies.html
{% extends 'main_shared.html' %}
{% load static %}
{% block title %}study Buddies{% endblock %}
{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
  <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
  </button>
  {{ message }}
</div>
{% endfor %}
{% endif %}
<div class="row mb-3">
  <form action="{% url 'study_buddies:view_all_study_buddies' %}" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-3">
        <div class="mb-3">
          <label for="time_zone" class="form-label">Time Zone</label>
          <input type="text" id="time_zone" class="form-control" name="time_zone_" list="time_zones">
          <datalist id="time_zones">
            {% for tz in time_zones %}
            <option value="{{tz}}"></option>
            {% endfor %}
          </datalist>
        </div>
      </div>
      <div class="col-md-3">
        <div id="exam_date" class="mb-3">
          <label for="exam_date" class="form-label"> Exam Date</label>
          <input type="date" name="exam_date" class="datepicker dateinput form-control" data-date-format="YYYY-MM-DD"
            id="exam_date">
        </div>
      </div>
      <!-- <div class="col-md-4">
          <div class="mb-3">
            <label for="availability" class="form-label">Day</label>
            <input type="text" id="availability" class="form-control" name="availability">
          </div>
        </div> -->
      <div class="col-md-4">
        <div class="mb-3">
          <label for="online_offline" class="form-label">Day</label>
          <select id="day" class="form-select" name="day">
            <option value=""></option>
            <option value="MONDAY">Monday</option>
            <option value="TUESDAY">Tuesday</option>
            <option value="WEDNESDAY">Wednesday</option>
            <option value="THURSDAY">Thursday</option>
            <option value="FRIDAY">Friday</option>
            <option value="SATURDAY">Saturday</option>
            <option value="SUNDAY">Sunday</option>
          </select>
        </div>
      </div>
      <div class="col-md-2 d-flex flex-column" style="margin-top: auto !important; margin-bottom: 1.1em !important;">

        <button type="submit" class="btn btn-primary">
          Find <span class="tf-icons bx bx-search-alt me-1"></span>
        </button>
      </div>

    </div>

  </form>
</div>
<div class="row mb-5">
  <div class="col-md-12">
    <h1 class="display-6 mb-0" style="color:#0080FF;"><span>{{candidates}} candidates available </span></h1>
    {% if type == 1 %}
    <br>
    <span>
      <i>Search Results for >></i>
      {% if time_zone %}
      Time zone: <b>{{time_zone}} </b>
      {% endif %}
      {% if exam_date %}
      Exam date: <b>{{exam_date}}</b>
      {% endif %}
      {% if day %}
      Day: <b>{{day}}</b>
      {% endif %}
      <a href="{% url 'study_buddies:view_all_study_buddies' %}"><span class="tf-icons bx bx-x me-1"
          style="color: red; font-size: 30px;"></span></a>
    </span>
    {% endif %}
  </div>
</div>
{% for item in obj %}
<div class="row mb-5">

  <div class="col-md">
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-3">
          <a href="{% url 'accounts:public_profile' item.id %}">
            {% if item.user_general_additional_info.profile_picture %}
            <img class="card-img card-img-left" src="{{item.user_general_additional_info.profile_picture.url}}"
              alt="{{item.get_full_name}}" style="height:250px;width:100%;object-fit:cover; object-position: 100% 0;">
            {% else %}
            <img class="card-img card-img-left" src="  {% static 'assets/img/placeholder.jpg' %}"
              alt="{{item.get_full_name}}" style="height:250px;width:100%;object-fit:cover; object-position: 100% 0;">
            {% endif %}
          </a>
        </div>
        <div class="col-md-9">
          <div class="card-body">
            <h5 class="card-title">{{item.get_full_name|title}}</h5>
         
            <div class="row">
              <div class="col-md-4">
                <a href="{% url 'meeting_calendar:book_a_meeting_v1' item.id %}" class="btn btn-primary">
                  {% if obj.role == 'Candidate' %}
                  Propose Meeting
                  {% else %}
                  Book Session
                  {% endif %}
                </a>
              </div>
              <div class="col-md-4">Time Zone : {{item.user_general_additional_info.time_zone}} </div>
              <!-- <div class="col-md-4"><a href="{% url 'meeting_calendar:availability' item.id %}">See Availability</a>
              </div> -->
              <div class="col-md-4">Exam Date: {{item.study_buddy_additional_info.exam_date}}</div>
            </div>
            <div class="row mt-3">
              <div class="col-md-4 col-xl-4">
                <div class="card shadow-none bg-transparent border border-info mb-3">
                  <div class="card-body text-center">
                    <h5 class="card-title">{{item.meeting_attendance}}</h5>
                    <p class="card-text"><a href="">Meetings</a> </p>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-xl-4">
                <div class="card shadow-none bg-transparent border border-info mb-3">
                  <div class="card-body text-center">
                    <h5 class="card-title">{{item.reliability|floatformat:0}}%</h5>
                    <p class="card-text"><a href="">Reliability</a> </p>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-xl-4">
                <div class="card shadow-none bg-transparent border border-info mb-3">
                  <div class="card-body text-center">
                    <h5 class="card-title"> {% include 'snippets/ratings.html' with obj=item %}</h5>
                    <p class="card-text"><a href="">Reviews</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% if obj %}
{% include 'snippets/pagination.html' with items=obj %}
{% endif %}

{% endblock %}